/*
 * Copyright (c) 2026. caoccao.com Sam Cao
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.caoccao.javet.swc4j.compiler;

import com.caoccao.javet.swc4j.compiler.memory.CompilationContext;
import com.caoccao.javet.swc4j.compiler.memory.ScopedEnumRegistry;
import com.caoccao.javet.swc4j.compiler.memory.ScopedJavaClassRegistry;
import com.caoccao.javet.swc4j.compiler.memory.ScopedTypeAliasRegistry;

import java.util.HashMap;
import java.util.Map;

public final class ByteCodeCompilerMemory {
    private final Map<String, byte[]> byteCodeMap;
    private final CompilationContext compilationContext;
    private final ScopedEnumRegistry scopedEnumRegistry;
    private final ScopedJavaClassRegistry scopedJavaClassRegistry;
    private final ScopedTypeAliasRegistry scopedTypeAliasRegistry;

    public ByteCodeCompilerMemory() {
        byteCodeMap = new HashMap<>();
        compilationContext = new CompilationContext();
        scopedEnumRegistry = new ScopedEnumRegistry();
        scopedJavaClassRegistry = new ScopedJavaClassRegistry();
        scopedTypeAliasRegistry = new ScopedTypeAliasRegistry();
    }

    public void enterScope() {
        scopedEnumRegistry.enterScope();
//        scopedJavaClassRegistry.enterScope();
        scopedTypeAliasRegistry.enterScope();
    }

    public void exitScope() {
        scopedEnumRegistry.exitScope();
//        scopedJavaClassRegistry.exitScope();
        scopedTypeAliasRegistry.exitScope();
    }

    /**
     * Get the bytecode map containing generated bytecode for all compiled classes.
     *
     * @return the bytecode map
     */
    public Map<String, byte[]> getByteCodeMap() {
        return byteCodeMap;
    }

    /**
     * Get the current CompilationContext.
     *
     * @return the current compilation context
     */
    public CompilationContext getCompilationContext() {
        return compilationContext;
    }

    public ScopedEnumRegistry getScopedEnumRegistry() {
        return scopedEnumRegistry;
    }

    public ScopedJavaClassRegistry getScopedJavaClassRegistry() {
        return scopedJavaClassRegistry;
    }

    public ScopedTypeAliasRegistry getScopedTypeAliasRegistry() {
        return scopedTypeAliasRegistry;
    }

    public void reset() {
        byteCodeMap.clear();
        compilationContext.reset();
        scopedEnumRegistry.clear();
        scopedJavaClassRegistry.clear();
        scopedTypeAliasRegistry.clear();
    }

    public void resetCompilationContext() {
        compilationContext.reset();
    }
}
