/*
 * Copyright (c) 2026. caoccao.com Sam Cao
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.caoccao.javet.swc4j.compiler;

import com.caoccao.javet.swc4j.ast.interfaces.ISwc4jAst;
import com.caoccao.javet.swc4j.compiler.memory.*;
import com.caoccao.javet.swc4j.exceptions.Swc4jByteCodeCompilerException;

import java.util.HashMap;
import java.util.Map;

public final class ByteCodeCompilerMemory {
    private final Map<String, byte[]> byteCodeMap;
    private final CompilationContext compilationContext;
    private final ScopedJavaTypeRegistry scopedJavaTypeRegistry;
    private final ScopedStandaloneFunctionRegistry scopedStandaloneFunctionRegistry;
    private final ScopedTypeAliasRegistry scopedTypeAliasRegistry;

    public ByteCodeCompilerMemory() {
        byteCodeMap = new HashMap<>();
        compilationContext = new CompilationContext();
        scopedJavaTypeRegistry = new ScopedJavaTypeRegistry();
        scopedStandaloneFunctionRegistry = new ScopedStandaloneFunctionRegistry();
        scopedTypeAliasRegistry = new ScopedTypeAliasRegistry();
    }

    public void enterScope() {
        scopedStandaloneFunctionRegistry.enterScope();
        scopedTypeAliasRegistry.enterScope();
    }

    public void exitScope() {
        scopedStandaloneFunctionRegistry.exitScope();
        scopedTypeAliasRegistry.exitScope();
    }

    /**
     * Get the bytecode map containing generated bytecode for all compiled classes.
     *
     * @return the bytecode map
     */
    public Map<String, byte[]> getByteCodeMap() {
        return byteCodeMap;
    }

    /**
     * Get the current CompilationContext.
     *
     * @return the current compilation context
     */
    public CompilationContext getCompilationContext() {
        return compilationContext;
    }

    public ScopedJavaTypeRegistry getScopedJavaTypeRegistry() {
        return scopedJavaTypeRegistry;
    }

    public ScopedStandaloneFunctionRegistry getScopedStandaloneFunctionRegistry() {
        return scopedStandaloneFunctionRegistry;
    }

    public ScopedTypeAliasRegistry getScopedTypeAliasRegistry() {
        return scopedTypeAliasRegistry;
    }

    public void reset() {
        byteCodeMap.clear();
        compilationContext.reset();
        scopedJavaTypeRegistry.clear();
        scopedStandaloneFunctionRegistry.clear();
        scopedTypeAliasRegistry.clear();
    }

    public void resetCompilationContext() {
        compilationContext.reset();
    }

    /**
     * Reset the compilation context for a specific method type.
     *
     * @param isStatic true if this is for a static method (no 'this' parameter)
     */
    public void resetCompilationContext(boolean isStatic) {
        compilationContext.reset(isStatic);
    }

    /**
     * Resolves a simple class name to its JavaTypeInfo.
     * First checks the type alias registry, then the java type registry.
     *
     * @param className the class name to resolve
     * @param ast       the AST node for error reporting
     * @return the JavaTypeInfo
     * @throws Swc4jByteCodeCompilerException if the type is not found
     */
    public JavaTypeInfo resolveType(String className, ISwc4jAst ast) throws Swc4jByteCodeCompilerException {
        // First try to resolve from the type alias registry
        String resolvedType = scopedTypeAliasRegistry.resolve(className);
        if (resolvedType != null) {
            String internalName = resolvedType.replace('.', '/');
            int lastSlash = internalName.lastIndexOf('/');
            String packageName = lastSlash >= 0 ? resolvedType.substring(0, lastSlash).replace('/', '.') : "";
            return new JavaTypeInfo(className, packageName, internalName);
        }

        // Then try to resolve from the java type registry
        var javaTypeInfo = scopedJavaTypeRegistry.resolve(className);
        if (javaTypeInfo != null) {
            return javaTypeInfo;
        }

        throw new Swc4jByteCodeCompilerException(ast,
                "Type '" + className + "' not found. Did you forget to import it?");
    }
}
