/*
 * Copyright (c) 2026. caoccao.com Sam Cao
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.caoccao.javet.swc4j.compiler;

import java.util.Map;

/**
 * Runs compiled bytecode by loading classes and creating runners for method invocation.
 */
public class ByteCodeRunner {
    /**
     * The class loader for loading bytecode.
     */
    protected final ByteArrayClassLoader classLoader;

    /**
     * Constructs a ByteCodeRunner with the provided bytecode map and parent class loader.
     *
     * @param byteCodeMap       the map of class names to bytecode
     * @param parentClassLoader the parent class loader
     */
    public ByteCodeRunner(Map<String, byte[]> byteCodeMap, ClassLoader parentClassLoader) {
        this.classLoader = new ByteArrayClassLoader(byteCodeMap, parentClassLoader);
    }

    /**
     * Creates an instance runner for the specified class with constructor arguments.
     *
     * @param className       the fully qualified class name
     * @param constructorArgs the constructor arguments
     * @return a ByteCodeClassRunner for instance method invocation
     * @throws ClassNotFoundException if the class cannot be found
     */
    public ByteCodeClassRunner createInstanceRunner(String className, Object... constructorArgs) throws ClassNotFoundException {
        return ByteCodeClassRunner.createInstance(getClass(className), constructorArgs);
    }

    /**
     * Creates a static runner for the specified class.
     *
     * @param className the fully qualified class name
     * @return a ByteCodeClassRunner for static method invocation
     * @throws ClassNotFoundException if the class cannot be found
     */
    public ByteCodeClassRunner createStaticRunner(String className) throws ClassNotFoundException {
        return ByteCodeClassRunner.createStatic(getClass(className));
    }

    /**
     * Gets the class with the specified name.
     *
     * @param className the fully qualified class name
     * @return the loaded Class object
     * @throws ClassNotFoundException if the class cannot be found
     */
    public Class<?> getClass(String className) throws ClassNotFoundException {
        return classLoader.getClass(className);
    }

    /**
     * Gets the default class (named "$") generated by the compiler.
     *
     * @return the default Class object
     * @throws ClassNotFoundException if the default class cannot be found
     */
    public Class<?> getDefaultClass() throws ClassNotFoundException {
        return getClass("$");
    }
}
