/*
 * Copyright (c) 2026. caoccao.com Sam Cao
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.caoccao.javet.swc4j.compiler.utils.json;

/**
 * Static facade for JSON serialization and parsing.
 * Generated bytecode calls these static methods. At runtime, they delegate to
 * the configured {@link JsonProvider} instance.
 */
public final class JsonUtils {
    /**
     * Sentinel value representing JavaScript's {@code undefined}.
     * When returned from a replacer function, the property is omitted from the output.
     * For array elements, it serializes as {@code null}.
     */
    public static final Object UNDEFINED = new Object() {
        @Override
        public String toString() {
            return "undefined";
        }
    };

    private static volatile JsonProvider provider = DefaultJsonProvider.INSTANCE;

    private JsonUtils() {
    }

    /**
     * Gets the current JSON provider.
     *
     * @return the current provider
     */
    public static JsonProvider getProvider() {
        return provider;
    }

    /**
     * Parses a JSON string into Java objects.
     *
     * @param json the JSON string to parse
     * @return the parsed Java object
     */
    public static Object parse(String json) {
        return provider.parse(json);
    }

    /**
     * Sets the JSON provider. If null, falls back to {@link DefaultJsonProvider#INSTANCE}.
     *
     * @param provider the provider to use
     */
    public static void setProvider(JsonProvider provider) {
        JsonUtils.provider = (provider != null) ? provider : DefaultJsonProvider.INSTANCE;
    }

    /**
     * Serializes a Java object to a JSON string.
     *
     * @param value the value to serialize
     * @return the JSON string
     */
    public static String stringify(Object value) {
        return provider.stringify(value);
    }

    /**
     * Serializes a Java object to a JSON string with optional replacer and space.
     *
     * @param value    the value to serialize
     * @param replacer the replacer ({@link java.util.function.BiFunction} or {@link java.util.ArrayList} whitelist or null)
     * @param space    the indentation (Number or String or null)
     * @return the JSON string
     */
    public static String stringify(Object value, Object replacer, Object space) {
        return provider.stringify(value, replacer, space);
    }
}
