/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caoccao_javet_swc4j_SWCNative */

#ifndef _Included_com_caoccao_javet_swc4j_SWCNative
#define _Included_com_caoccao_javet_swc4j_SWCNative
#ifdef __cplusplus
extern "C" {
#endif
#undef com_caoccao_javet_swc4j_SWCNative_BUFFER_LENGTH
#define com_caoccao_javet_swc4j_SWCNative_BUFFER_LENGTH 4096L
#undef com_caoccao_javet_swc4j_SWCNative_MIN_LAST_MODIFIED_GAP_IN_MILLIS
#define com_caoccao_javet_swc4j_SWCNative_MIN_LAST_MODIFIED_GAP_IN_MILLIS 60000i64
/*
 * Class:     com_caoccao_javet_swc4j_SWCNative
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_caoccao_javet_swc4j_SWCNative_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
